### ISSUE TITLE
USER STORY: Log in using username and password

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlistsharer#1]
As a **Site User** I can **log in to the site with my username and password** so that **I can use all site features**

# Acceptance Criteria

 - Clicking on the login link takes me to the log in page
 - The page contains a form with Username, Password and a submit button
 - Filling in the form with correct data logs me in
 - Once logged in I am taken to the home page

# Tasks

- [ ] Add User model
- [ ] Add base template to allauth templates
- [ ] Redirect to the home page
- [ ] Manually test sign up process
- [ ] Add HTML and CSS
