### ISSUE TITLE
USER STORY: View numbers agreeing or disagreeing with a setlist

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlistsharer#10]
As a **Site User** I can **see how many people have agreed or disagreed with a setlist** so that **I can gauge its accuracy**

# Acceptance Criteria

 - The numbers agreeing or disagreeing with a setlist are shown on the site

# Tasks

- [ ] Add numbers agreeing to a setlist to the home page
- [ ] Add numbers agreeing to a setlist to the setlist/detail page
- [ ] Add numbers disagreeing to a setlist to the home page
- [ ] Add numbers disagreeing to a setlist to the setlist/detail page
