### ISSUE TITLE
USER STORY: Submit photo

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlistsharer#11]
As a **Site User** I can **update my personal information** so that **any changes can be made or edited**

# Acceptance Criteria

 - I can update my email address
 - I can update my password

# Tasks

- [ ] Create accounts/edit url, view and template
- [ ] Include a form with relevant fields in template
- [ ] Save changes to database
- [ ] Manually test updating user info
