### ISSUE TITLE
USER STORY: Add songs to the database

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlistsharer#16]
As a **Site Admin** I can **create a list of the bands songs** so that **users can choose from these songs and ensure song titles are correct**

# Acceptance Criteria

 - I can add songs through the admin 

# Tasks

- [ ] Create Venue model
- [ ] Create Gig model
- [ ] Create Song model
- [ ] Create Release model
- [ ] Create Setlist model
- [ ] Add User model
