### ISSUE TITLE
USER STORY: Sign up using username and password

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlistsharer#2]
As a **Site User** I can **create a username and password** so that **I can sign up to the site**

# Acceptance Criteria

 - I can enter my information needed to sign up to the site
 - The page contains a form with Username, Password, Password Confirmation fields and a submit button
 - My entered information is validated
 - My entered information is saved

# Tasks

- [ ] Create tests
- [ ] Install and set up Allauth
- [ ] Add base template to Allauth templates
- [ ] Manually test sign up process
- [ ] Add HTML and CSS
