### ISSUE TITLE
USER STORY: View gigs on home page

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlistsharer#7]
As a **Site User** I can **see a list of gigs** so that **I can see which gigs are covered on the site**

# Acceptance Criteria

 - The home page has a list of gigs
 - The list shows the date, venue name and city

# Tasks

- [ ] Create test
- [ ] Create home app
- [ ] Create a base template
- [ ] Create the view code
- [ ] Create a template 
- [ ] Connect up URLs
- [ ] Display gig info on home template
- [ ] Update placeholder site info text
