### ISSUE TITLE
USER STORY: Agree/disagree with a setlist

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlistsharer#9]
As a **Site User** I can **agree or disagree with a setlist** so that **I feel personally involved with the site**

# Acceptance Criteria

 - When looking at a setlist I can either agree or disagree with it
 - Clicking on agree/disagree when I have previously removes my agree/disagree
 - Clicking on the opposite of my previous agree/disagree removes that and adds it to the newly clicked option

# Tasks

- [ ] Add agree and disagree buttons to setlist details
- [ ] Create setlist/agree and setlist/disagree view
- [ ] Manually test agreeing/disagreeing
